--- Habilidades

INSERT INTO habilidade (id_habilidade, tipo_habilidade, tipo_classe, numero, descricao, cooldown, custo_mana, ranque) 
VALUES
(1, 'ativa', 'saber', 1, 'Corte Rápido', 5, 10, 'a'),
(2, 'passiva', 'lancer', 2, 'Agressividade Natural', NULL, 0, 'b'),
(3, 'noble_phantasm', 'archer', 3, 'Flecha Divina', 10, 30, 'ex'),
(4, 'habilidade_especial', 'rider', 4, 'Cavalgada Fantástica', 8, 20, 's'),
(5, 'ativa', 'caster', 5, 'Feitiço do Vento', 6, 15, 'a'),
(6, 'passiva', 'assassin', 6, 'Mestre das Sombras', NULL, 0, 'c'),
(7, 'noble_phantasm', 'berserker', 7, 'Fúria Descontrolada', 12, 40, 'sss'),
(8, 'habilidade_especial', 'saber', 8, 'Espada dos Céus', 7, 25, 'ss'),
(9, 'ativa', 'lancer', 9, 'Lança Veloz', 4, 10, 'b'),
(10, 'passiva', 'archer', 10, 'Precisão Extrema', NULL, 0, 'a'),
(11, 'noble_phantasm', 'rider', 11, 'Carruagem Divina', 10, 35, 'ex'),
(12, 'habilidade_especial', 'caster', 12, 'Encantamento Supremo', 9, 20, 'ss'),
(13, 'ativa', 'assassin', 13, 'Ataque Furtivo', 5, 15, 'b'),
(14, 'passiva', 'berserker', 14, 'Regeneração Rápida', NULL, 0, 'd'),
(15, 'noble_phantasm', 'saber', 15, 'Golpe Final', 15, 50, 'sss'),
(16, 'habilidade_especial', 'lancer', 16, 'Lança do Destino', 8, 30, 's'),
(17, 'ativa', 'archer', 17, 'Disparo Duplo', 3, 12, 'a'),
(18, 'passiva', 'rider', 18, 'Velocidade Sobrenatural', NULL, 0, 'b'),
(19, 'noble_phantasm', 'caster', 19, 'Magia Proibida', 14, 45, 'ex'),
(20, 'habilidade_especial', 'assassin', 20, 'Camuflagem Perfeita', 6, 18, 'ss'),
(21, 'ativa', 'berserker', 21, 'Fúria Devastadora', 7, 22, 'a'),
(22, 'passiva', 'saber', 22, 'Resistência Absoluta', NULL, 0, 'c'),
(23, 'noble_phantasm', 'lancer', 23, 'Ataque Divino', 10, 40, 'sss'),
(24, 'habilidade_especial', 'archer', 24, 'Olho de Águia', 5, 20, 's'),
(25, 'ativa', 'rider', 25, 'Investida Selvagem', 6, 18, 'b'),
(26, 'passiva', 'caster', 26, 'Sabedoria Infinita', NULL, 0, 'a'),
(27, 'noble_phantasm', 'assassin', 27, 'Assassinato Perfeito', 12, 35, 'ss'),
(28, 'habilidade_especial', 'berserker', 28, 'Força Bruta', 9, 25, 'a'),
(29, 'ativa', 'saber', 29, 'Corte do Dragão', 6, 15, 's'),
(30, 'passiva', 'lancer', 30, 'Defesa Impenetrável', NULL, 0, 'b');