INSERT INTO dialogo (id_dialogo, fala) VALUES
(1, 'Protagonista: Quem é você? Eu não me lembro de ter visto você antes.'),
(2, 'Artoria: Eu sou Artoria Pendragon. E você? Não parece ser daqui.'),
(3, 'Protagonista: Meu nome não importa agora. O que você faz aqui?'),
(4, 'Artoria: Estou aqui para proteger este reino. Todos que ameaçam a paz terão de passar por mim.'),
(5, 'Protagonista: Então, você é uma cavaleira? Achei que esses tempos já tinham passado.'),
(6, 'Artoria: Os tempos podem mudar, mas a honra de um cavaleiro não.'),
(7, 'Protagonista: Quem você pensa que é? A sua presença é imponente...'),
(8, 'Gilgamesh: Hmph. Eu sou Gilgamesh, o Rei dos Heróis. E você, mortal insignificante?'),
(9, 'Protagonista: Gilgamesh? O Rei dos Heróis? Nunca ouvi falar de você.'),
(10, 'Gilgamesh: Que ignorância! Não saber meu nome é uma ofensa. Mas, talvez, eu possa perdoar sua insolência, só desta vez.'),
(11, 'Protagonista: Perdão? Não estou pedindo perdão. Apenas tentando entender com quem estou lidando.'),
(12, 'Gilgamesh: Você deve se sentir honrado por estar na minha presença. Poucos têm essa sorte.'),
(13, 'Protagonista: Quem é você? Por que está me seguindo?'),
(14, 'Medusa: Eu sou Medusa. Não se assuste, estou apenas observando.'),
(15, 'Protagonista: Observar? E qual é o seu interesse em mim?'),
(16, 'Medusa: Eu tenho curiosidade sobre os heróis que atravessam este mundo. Você é um deles.'),
(17, 'Protagonista: Não tenho certeza se isso é um elogio ou uma ameaça.'),
(18, 'Medusa: Não é nenhuma das duas coisas. Apenas uma forma de dizer que eu estarei de olho em você.'),
(19, 'Protagonista: Quem é você? Parece que você está me observando.'),
(20, 'Jeanne: Eu sou Jeanne dArc. Não tema, não tenho intenções hostis.'),
(21, 'Protagonista: Jeanne dArc? A lendária heroína? O que está fazendo aqui?'),
(22, 'Jeanne: Minha missão é proteger e guiar os que lutam por justiça. E parece que você está nessa jornada.'),
(23, 'Protagonista: Então, você está aqui para me ajudar?'),
(24, 'Jeanne: Exatamente. Estou aqui para assegurar que o caminho para a vitória seja justo e verdadeiro.'),
(25, 'Protagonista: Quem é você? Nunca te vi antes.'),
(26, 'Emiya: Sou Emiya. Pareço ter chegado a um lugar inesperado.'),
(27, 'Protagonista: Emiya, hein? E qual é o seu objetivo aqui?'),
(28, 'Emiya: Meu objetivo é proteger e lutar contra aqueles que ameaçam a paz. E você, o que busca?'),
(29, 'Protagonista: Estou em busca de respostas e de proteger aqueles que não podem se defender.'),
(30, 'Emiya: Parece que temos interesses em comum. Talvez possamos trabalhar juntos para alcançar nossos objetivos.'),
(31, 'Protagonista: Quem é você? Nunca te vi antes por aqui.'),
(32, 'Karna: Sou Karna, um guerreiro e defensor. E quem seria você, viajante?'),
(33, 'Protagonista: Eu sou o protagonista desta jornada. O que traz um guerreiro como você a este lugar?'),
(34, 'Karna: Meu propósito é combater o mal e proteger os inocentes. Tenho a sensação de que nossos caminhos estão entrelaçados.'),
(35, 'Protagonista: Você parece determinado. Talvez possamos unir forças para enfrentar os desafios que virão.'),
(36, 'Karna: Concordo. Uma aliança pode ser vantajosa para ambos. Estou pronto para lutar ao seu lado.'),
(37, 'Protagonista: Quem é você? Seu porte é imponente.'),
(38, 'Heracles: Sou Heracles, um herói conhecido por meus feitos lendários. E você, quem é?'),
(39, 'Protagonista: Sou apenas um viajante em busca de respostas. O que faz um herói como você aqui?'),
(40, 'Heracles: Estou em uma missão para enfrentar as forças do mal e buscar justiça. O destino parece ter nos reunido.'),
(41, 'Protagonista: Com suas habilidades, talvez possamos enfrentar os desafios juntos. O que acha?'),
(42, 'Heracles: Uma parceria pode ser útil. Aceito a proposta. Vamos lutar lado a lado.'),
(43, 'Protagonista: Quem é você? Nunca te vi antes.'),
(44, 'Mash: Sou Mash Kyrielight, uma Demi-Servant. E você, quem é?'),
(45, 'Protagonista: Sou um viajante em busca de aliados. O que faz uma Demi-Servant por aqui?'),
(46, 'Mash: Estou aqui para proteger e apoiar meu mestre. Parece que nossos caminhos se cruzaram por uma razão.'),
(47, 'Protagonista: Se precisar de ajuda ou se houver algo em que eu possa contribuir, conte comigo.'),
(48, 'Mash: Agradeço a oferta. Juntos, podemos enfrentar qualquer desafio que apareça em nosso caminho.'),
(43, 'Protagonista: Quem é você? Nunca te vi antes.'),
(44, 'Mash: Sou Mash Kyrielight, uma Demi-Servant. E você, quem é?'),
(45, 'Protagonista: Sou um viajante em busca de aliados. O que faz uma Demi-Servant por aqui?'),
(46, 'Mash: Estou aqui para proteger e apoiar meu mestre. Parece que nossos caminhos se cruzaram por uma razão.'),
(47, 'Protagonista: Se precisar de ajuda ou se houver algo em que eu possa contribuir, conte comigo.'),
(48, 'Mash: Agradeço a oferta. Juntos, podemos enfrentar qualquer desafio que apareça em nosso caminho.'),

(49, 'Protagonista: Quem é você? Seu nome não me é familiar.'),
(50, 'Angra Mainyu: Eu sou Angra Mainyu, a manifestação do mal. E você é apenas um mero mortal perdido.'),
(51, 'Protagonista: Então você é uma ameaça. O que quer de mim?'),
(52, 'Angra Mainyu: Não tenho interesse em seus desejos ou motivações. Apenas esteja ciente de que minha presença é um mal que não deve ser ignorado.'),
(53, 'Protagonista: Não vou deixar que o mal prevaleça. Se for necessário, lutarei contra você.'),
(54, 'Angra Mainyu: Típico de um herói. Prepare-se para uma batalha que você não poderá esquecer.'),

(55, 'Protagonista: Quem é você? Não te conheço.'),
(56, 'Cu Chulainn: Eu sou Cu Chulainn, o herói de Ulster. E você, um viajante perdido em meu caminho.'),
(57, 'Protagonista: Um herói, huh? O que está fazendo aqui?'),
(58, 'Cu Chulainn: Minha jornada é para defender meu nome e minha terra. O que você busca em sua jornada?'),
(59, 'Protagonista: Estou em busca de respostas e de proteger aqueles que amo. Talvez possamos ajudar um ao outro.'),
(60, 'Cu Chulainn: Respostas e proteção, você diz? Talvez, mas lembre-se, heróis têm seus próprios desafios. Esteja preparado para o que virá.'),

(67, 'Protagonista: Quem é você? Não te conheço.'),
(68, 'Scáthach: Eu sou Scáthach, a rainha das sombras e mestra de heróis. E você, quem é que se atreve a me desafiar?'),
(69, 'Protagonista: Eu sou apenas um viajante buscando meu caminho. O que faz uma figura tão imponente como você aqui?'),
(70, 'Scáthach: Estou aqui para cumprir meu dever e proteger o que é meu. E você, o que procura em meio a essa jornada?'),
(71, 'Protagonista: Procuro poder e conhecimento para enfrentar os desafios que virão. Talvez possamos aprender algo um com o outro.'),
(72, 'Scáthach: Poder e conhecimento são armas perigosas. Se você realmente deseja crescer, deve estar preparado para o custo. Cuidado com o que deseja.'),

(73, 'Protagonista: Quem é você? Nunca te vi antes.'),
(74, 'Merlin: Ah, um desconhecido! Eu sou Merlin, o mago das lendas e do engano. E você, quem é você para me procurar?'),
(75, 'Protagonista: Sou apenas alguém em busca de respostas. O que faz um mago como você aqui?'),
(76, 'Merlin: Ah, respostas, sempre tão evasivas. Estou aqui para observar e, quem sabe, ajudar aqueles que são dignos de um pouco de magia.'),
(77, 'Protagonista: Se você tem o poder de ajudar, então talvez possamos fazer um acordo. Estou disposto a aprender e a colaborar.'),
(78, 'Merlin: Interessante! Então você tem a mente aberta para o mistério e a magia. Muito bem, talvez possamos encontrar um propósito comum.'),

(79, 'Protagonista: Quem é você? Parece ser alguém de grande importância.'),
(80, 'Lancelot: Eu sou Lancelot, um cavaleiro da Távola Redonda. E você, estranho, o que busca nesta terra?'),
(81, 'Protagonista: Procuro entender o que está acontecendo ao meu redor. Seus feitos são lendários, por que está aqui?'),
(82, 'Lancelot: Meu dever é proteger e lutar pelas causas justas. Se você está perdido, talvez eu possa ajudá-lo a encontrar seu caminho.'),
(83, 'Protagonista: Agradeço. Então, qual é o seu objetivo aqui? Como podemos colaborar?'),
(84, 'Lancelot: Meu objetivo é assegurar que a justiça prevaleça. Se suas intenções são nobres, talvez possamos unir nossas forças em prol de um bem maior.'),

(85, 'Protagonista: Quem é você? Sua presença é bastante imponente.'),
(86, 'Nero: Eu sou Nero, Imperatriz de Roma! Você deve sentir a grandiosidade de minha presença.'),
(87, 'Protagonista: Imperatriz? Então você é uma figura de grande poder e autoridade. O que faz aqui?'),
(88, 'Nero: Meu destino é governar e trazer glória ao meu império, mesmo neste novo mundo. E você, o que busca?'),
(89, 'Protagonista: Estou tentando entender o que está acontecendo e encontrar meu propósito.'),
(90, 'Nero: Se o seu propósito é digno, talvez eu possa ajudá-lo. O poder e a glória podem ser alcançados por aqueles que são valentes.'),

(91, 'Protagonista: Olá, quem é você? Nunca a vi antes.'),
(92, 'Tamamo: Ah, olá! Eu sou Tamamo Cat, uma poderosa serva com uma aparência fofa.'),
(93, 'Protagonista: Tamamo Cat? Sua aparência é um tanto... intrigante. O que faz aqui?'),
(94, 'Tamamo: Estou aqui para oferecer minha ajuda e orientação. Tenho habilidades mágicas que podem ser úteis para você.'),
(95, 'Protagonista: Isso é ótimo! O que exatamente você pode fazer?'),
(96, 'Tamamo: Posso usar minha magia para curar e proteger, além de ter habilidades para criar ilusões. Juntos, podemos enfrentar qualquer desafio.'),

(103, 'Protagonista: Olá, quem é você? Não estou familiarizado com sua aparência.'),
(104, 'Arjuna: Eu sou Arjuna, o arqueiro lendário da Índia. E você deve ser o novo herói que conheci.'),
(105, 'Protagonista: Arjuna, um prazer conhecê-lo. O que o traz aqui?'),
(106, 'Arjuna: Estou aqui para oferecer minha ajuda na batalha e compartilhar meu conhecimento em combate.'),
(107, 'Protagonista: Isso é excelente! O que você pode nos ensinar?'),
(108, 'Arjuna: Minha experiência com arcos e flechas é incomparável. Posso ensinar técnicas avançadas de tiro e estratégias de batalha.'),

(109, 'Protagonista: Quem é você? Nunca a vi antes.'),
(110, 'Medb: Eu sou Medb, a Rainha dos Connacht. E você deve ser o novo herói em quem todos falam.'),
(111, 'Protagonista: Medb, é um prazer conhecê-la. O que deseja de mim?'),
(112, 'Medb: Apenas ver o que você é capaz. Além disso, a realeza deve saber quem são seus aliados.'),
(113, 'Protagonista: Entendo. Estou aqui para enfrentar desafios e proteger aqueles que precisam.'),
(114, 'Medb: Então você é um verdadeiro guerreiro. Isso pode ser interessante. Talvez possamos trabalhar juntos em breve.'),

(115, 'Protagonista: Você deve ser Siegfried, o herói das lendas. É uma honra conhecê-lo.'),
(116, 'Siegfried: A honra é minha. E você é o novo aventureiro que todos mencionam, certo?'),
(117, 'Protagonista: Sim, estou aqui para enfrentar desafios e cumprir minha missão.'),
(118, 'Siegfried: Excelente. Todos nós temos um papel a desempenhar em nossas histórias. O que busca nesta jornada?'),
(119, 'Protagonista: Quero proteger os inocentes e restaurar a ordem. E você, o que o trouxe aqui?'),
(120, 'Siegfried: Busco testar minha força e habilidades, além de ajudar aqueles que precisam. Talvez nossos caminhos se cruzem novamente.'),

(121, 'Protagonista: Você deve ser François. É um prazer encontrá-lo.'),
(122, 'François: O prazer é meu. Ouvi falar muito sobre suas aventuras. O que traz você até aqui?'),
(123, 'Protagonista: Estou em uma missão para resolver alguns problemas que surgiram recentemente. E você, o que faz aqui?'),
(124, 'François: Estou aqui para explorar e buscar novos desafios. Sempre há algo a aprender e a conquistar.'),
(125, 'Protagonista: Parece que temos objetivos semelhantes. Talvez possamos ajudar um ao outro.'),
(126, 'François: Concordo. Juntos, nossas chances de sucesso são maiores. Vamos ver o que o destino nos reserva.'),

(127, 'Protagonista: Olá, você deve ser Elizabeth. É bom conhecê-la.'),
(128, 'Elizabeth: Ah, sim, sou eu! E você é o famoso protagonista de quem todos falam. Como posso ajudar?'),
(129, 'Protagonista: Estou em busca de informações sobre alguns eventos recentes. Você tem algo que possa me ajudar?'),
(130, 'Elizabeth: Bem, eu sou especializada em lendas e histórias antigas. Talvez eu possa ter alguma pista para você.'),
(131, 'Protagonista: Isso seria ótimo. O que você sabe sobre as últimas ocorrências?'),
(132, 'Elizabeth: Tenho alguns documentos e relatos que podem ser úteis. Vamos começar a investigação juntos.'),

(133, 'Protagonista: Você é Napoleon, não é? Ouvi falar muito sobre suas conquistas.'),
(134, 'Napoleon: Sim, sou eu. E você é o novo herói que está causando alvoroço por aqui, correto?'),
(135, 'Protagonista: Exatamente. Estou aqui para entender melhor o que está acontecendo e como posso ajudar.'),
(136, 'Napoleon: Uma atitude nobre. Eu tenho alguns conhecimentos estratégicos que podem ser valiosos para você.'),
(137, 'Protagonista: Isso seria incrível. O que você pode compartilhar sobre a situação atual?'),
(138, 'Napoleon: Vamos conversar mais sobre isso. Eu posso oferecer conselhos estratégicos e algumas informações cruciais.'),

(139, 'Protagonista: Quem é você? Seu aspecto é imponente e parece que você não pertence a este mundo.'),
(140, 'Altera: Eu sou Altera, a destruição que caminha entre os mundos. E você, quem é para me desafiar?'),
(141, 'Protagonista: Sou um herói tentando entender e enfrentar as ameaças que surgem. Parece que você é uma dessas ameaças.'),
(142, 'Altera: Herói, hm? Não vejo muita esperança em você. Mas, se quer provar algo, esteja preparado para desafios.'),
(143, 'Protagonista: Estou preparado. Mas, antes, gostaria de saber mais sobre suas intenções e seu propósito.'),
(144, 'Altera: Meu propósito é além da compreensão dos mortais. Mas, se desejar, posso mostrar-lhe um pouco do meu poder.'),

(145, 'Protagonista: Quem é você? Seu traje parece ser de um cavaleiro de uma era passada.'),
(146, 'Gawain: Eu sou Gawain, um cavaleiro da Távola Redonda. E você, o que faz aqui em meu caminho?'),
(147, 'Protagonista: Sou um viajante e estou em busca de aliados para enfrentar perigos. Parece que você é um guerreiro valoroso.'),
(148, 'Gawain: Eu aceito o título de guerreiro com honra. Se você está aqui para lutar ao lado da justiça, talvez possamos trabalhar juntos.'),
(149, 'Protagonista: A justiça é uma causa nobre. Estou aqui para lutar por um propósito maior e proteger aqueles que precisam.'),
(150, 'Gawain: Então, vamos unir forças. Um verdadeiro cavaleiro respeita a coragem dos outros e combate ao lado dos que têm um coração puro.'),

(151, 'Protagonista: Você parece ser um guerreiro experiente. Quem é você?'),
(152, 'Tristan: Meu nome é Tristan, um cavaleiro de Camelot. E você, qual é o seu propósito aqui?'),
(153, 'Protagonista: Estou em busca de aliados e forças para enfrentar os desafios que estão por vir. Parece que você tem habilidades notáveis.'),
(154, 'Tristan: Seus objetivos são nobres. Eu estou disposto a oferecer minha ajuda, mas devo saber mais sobre seus objetivos e intenções.'),
(155, 'Protagonista: Meu objetivo é proteger os inocentes e lutar contra o mal que ameaça este mundo. E você, o que o motiva a lutar?'),
(156, 'Tristan: Minha lealdade está com aqueles que precisam de ajuda e com a causa da justiça. Se nossos objetivos se alinharem, lutaremos juntos.'),

(157, 'Protagonista: Quem é você? Seu comportamento é bastante imponente.'),
(158, 'Mordred: Sou Mordred, a Cavaleira do Caos. E você, o que faz aqui?'),
(159, 'Protagonista: Estou em busca de aliados e também de respostas sobre os eventos recentes. Parece que você não é alguém comum.'),
(160, 'Mordred: Respostas, hein? Não tenho muito a oferecer a não ser força e determinação. Se precisar de uma aliada, pode contar comigo.'),
(161, 'Protagonista: Isso é bom de ouvir. Estou enfrentando desafios e poderia usar alguém com suas habilidades ao meu lado.'),
(162, 'Mordred: Então é assim que será. Se você puder me mostrar que é digno, estarei ao seu lado para enfrentar qualquer obstáculo.'),

(163, 'Protagonista: Quem é você? Parece que você tem uma presença impressionante.'),
(164, 'Cleópatra: Ah, meu querido visitante, sou Cleópatra, Rainha do Nilo. E você deve ser o famoso herói que está causando tanto alvoroço.'),
(165, 'Protagonista: Rainha Cleópatra, é um prazer conhecê-la. O que a traz a este lugar?'),
(166, 'Cleópatra: Meu destino é complexo e cheio de intrigas, como o de qualquer monarca. Estou aqui para observar e, se necessário, intervir.'),
(167, 'Protagonista: Sua presença aqui deve significar que algo importante está em jogo. Pode me dizer mais sobre o que está acontecendo?'),
(168, 'Cleópatra: Meu querido, tudo está em movimento e o equilíbrio pode ser alterado a qualquer momento. Se quiser saber mais, talvez deva se preparar para o inesperado.'),

(169, 'Protagonista: Quem é você? Sua presença é imponente e um tanto intimidante.'),
(170, 'Nightingale: Sou Nightingale, uma defensora dos que necessitam de ajuda. E você deve ser o intrépido aventureiro de quem ouvi falar.'),
(171, 'Protagonista: Nightingale, é uma honra conhecê-la. O que traz uma defensora como você para este lugar?'),
(172, 'Nightingale: Meu dever é proteger e servir. Estou aqui para assegurar que aqueles que estão em perigo recebam a assistência que merecem.'),
(173, 'Protagonista: Então, você está aqui para ajudar? O que posso fazer para apoiar sua causa?'),
(174, 'Nightingale: Seu desejo de ajudar é admirável. No entanto, a verdadeira ajuda vem com a compreensão das necessidades e a ação correta. Vamos trabalhar juntos para alcançar nossos objetivos.'),

(175, 'Protagonista: Olá, quem é você? Parece que você tem uma presença muito forte.'),
(176, 'Atalanta: Sou Atalanta, a caçadora. E você deve ser o novo rosto que vejo por aqui.'),
(177, 'Protagonista: Atalanta, um prazer conhecê-la. O que faz uma caçadora como você por estas terras?'),
(178, 'Atalanta: Estou aqui em busca de desafios e presas dignas. A caçada é uma arte e uma paixão para mim.'),
(179, 'Protagonista: Isso soa fascinante. Posso ajudar de alguma forma na sua busca ou caçada?'),
(180, 'Atalanta: Agradeço a oferta. Se puder fornecer informações ou assistência durante uma caçada, isso será valioso. Apenas esteja preparado para a imprevisibilidade que a natureza pode trazer.'),

(181, 'Protagonista: Olá, você deve ser Ivan. Não esperava encontrar alguém como você aqui.'),
(182, 'Ivan: Sim, sou eu. E você deve ser o novo visitante. Não vejo muitas pessoas por aqui.'),
(183, 'Protagonista: De fato. O que faz você por essas terras?'),
(184, 'Ivan: Estou em busca de novos desafios e oportunidades para provar minha força. E você, o que o trouxe até aqui?'),
(185, 'Protagonista: Estou em uma jornada para entender melhor este mundo e suas peculiaridades. Talvez possamos ajudar um ao outro.'),
(186, 'Ivan: Interessante. Se precisar de uma força adicional ou tiver informações úteis, não hesite em me chamar. A força está sempre à disposição daqueles que a merecem.'),

(187, 'Protagonista: Olá, você deve ser Da Vinci. O que está fazendo por aqui?'),
(188, 'Da Vinci: Ah, você deve ser o novo aventureiro! Estou aqui para buscar inspiração e talvez ajudar em algo interessante.'),
(189, 'Protagonista: Incrível! E o que você encontrou até agora?'),
(190, 'Da Vinci: Muitas coisas fascinantes, na verdade. Este lugar está repleto de enigmas e segredos esperando para serem descobertos.'),
(191, 'Protagonista: Parece que temos um objetivo em comum então. Posso contar com sua ajuda para desvendar esses mistérios?'),
(192, 'Da Vinci: Com certeza! Vamos explorar juntos e ver o que podemos descobrir. Quem sabe o que novas invenções ou descobertas nos aguardam?'),

(193, 'Protagonista: Você é Mata Hari, certo? O que faz aqui?'),
(194, 'Mata Hari: Sim, sou eu. Estou aqui para me envolver em eventos que possam me beneficiar. E você, quem é?'),
(195, 'Protagonista: Sou apenas um aventureiro. O que você espera encontrar aqui?'),
(196, 'Mata Hari: Em um lugar cheio de segredos e mistérios, há sempre algo valioso a se descobrir. Não é verdade?'),
(197, 'Protagonista: Com certeza. Talvez possamos colaborar para alcançar nossos objetivos.'),
(198, 'Mata Hari: Uma proposta interessante. Fico curiosa para ver até onde podemos chegar juntos. Vamos ver o que o destino nos reserva.'),

(199, 'Protagonista: Você é Spartacus? O lendário gladiador?'),
(200, 'Spartacus: Sim, sou eu. E você é? Um novo desafiante, talvez?'),
(201, 'Protagonista: Não exatamente. Estou apenas explorando este lugar. O que te traz aqui?'),
(202, 'Spartacus: A luta por liberdade e justiça nunca acaba. Mesmo aqui, busco o significado do meu legado.'),
(203, 'Protagonista: Entendo. Então, você continua lutando mesmo fora dos combates?'),
(204, 'Spartacus: A luta está em meu sangue. Enquanto houver opressão, minha batalha nunca estará completa.'),

(205, 'Protagonista: Você é... Ereshkigal? A deusa do submundo?'),
(206, 'Ereshkigal: Sim, sou eu. E quem é você, mortal, para me reconhecer?'),
(207, 'Protagonista: Apenas um viajante curioso. Nunca esperei encontrar uma divindade aqui.'),
(208, 'Ereshkigal: Curioso, você diz? A curiosidade pode ser uma força perigosa. O que deseja de mim?'),
(209, 'Protagonista: Apenas aprender sobre o que você faz e como chegou aqui. O que busca em sua existência?'),
(210, 'Ereshkigal: Meu reino é o domínio dos mortos e dos esquecidos. Busco equilíbrio e ordem em meio ao caos.'),

(211, 'Protagonista: Você é Romulus, o lendário fundador de Roma?'),
(212, 'Romulus: Sim, sou eu. E você, quem é que se atreve a me abordar com tal conhecimento?'),
(213, 'Protagonista: Sou apenas um viajante em busca de conhecimento. O que trouxe você até aqui?'),
(214, 'Romulus: O destino me trouxe. Roma e seus mistérios têm raízes profundas, até mesmo aqui.'),
(215, 'Protagonista: E qual é o seu propósito em nosso tempo?'),
(216, 'Romulus: Minha missão é proteger o legado de Roma e garantir que a grandeza de minha cidade nunca seja esquecida.'),

(217, 'Protagonista: Você é Billy the Kid? O famoso fora da lei?'),
(218, 'Billy the Kid: E quem mais poderia ser? Mas me diga, o que te traz a este canto do mundo?'),
(219, 'Protagonista: Ouvi falar das suas aventuras e queria entender mais sobre você e sua história.'),
(220, 'Billy the Kid: Bem, a minha história não é nada além de um monte de tiros e corridas. Mas se é isso que procura, eu posso te contar um pouco.'),
(221, 'Protagonista: Então, você não se arrepende das suas escolhas?'),
(222, 'Billy the Kid: Arrependimento é para os fracos. Eu vivi do meu jeito e, no fim, isso é tudo que importa.'),

(223, 'Protagonista: Você é Dante? O famoso caçador de demônios?'),
(224, 'Dante: Ah, mais um que me conhece pela fama. E quem é você?'),
(225, 'Protagonista: Sou alguém em busca de aliados poderosos. Ouvi que você é imbatível.'),
(226, 'Dante: Imbatível, hein? Bem, talvez eu possa te ajudar, mas só se você provar que é digno.'),
(227, 'Protagonista: O que você precisa para isso?'),
(228, 'Dante: Primeiro, mostre-me que tem coragem e habilidades. Só então veremos se podemos trabalhar juntos.'),

(229, 'Protagonista: Você é Cleópatra, a rainha do Egito?'),
(230, 'Cleópatra: Ah, que interessante! Parece que minha fama transcendeu os tempos. Quem é você?'),
(231, 'Protagonista: Sou alguém em busca de aliados. Ouvi que sua inteligência e charme são lendários.'),
(232, 'Cleópatra: Flattery will get you everywhere. Mas diga-me, o que você oferece em troca de minha aliança?'),
(233, 'Protagonista: Tenho habilidades e recursos que podem ser valiosos para ambos. Podemos formar uma parceria.'),
(234, 'Cleópatra: Muito bem, vamos ver se suas ações correspondem às suas palavras. Prove seu valor, e talvez eu considere sua proposta.'),

(235, 'Protagonista: Você é Leonidas, o rei espartano?'),
(236, 'Leonidas: Sim, sou ele. Quem se apresenta diante de um rei espartano?'),
(237, 'Protagonista: Sou um viajante buscando aliados e sabedoria. Ouvi falar das suas proezas em batalha.'),
(238, 'Leonidas: Hum... Sabedoria e aliados são preciosos. O que você oferece para ganhar minha atenção?'),
(239, 'Protagonista: Trago habilidades e estratégias que podem ser valiosas em combate. Juntos, podemos alcançar grandes feitos.'),
(240, 'Leonidas: Hmph, palavras são fáceis. Mostre-me sua coragem e determinação, e talvez você possa ganhar meu respeito.'),

(241, 'Protagonista: Você é Sun Tzu, o lendário estrategista?'),
(242, 'Sun Tzu: Sim, sou ele. O que busca de mim, viajante?'),
(243, 'Protagonista: Ouvi falar das suas táticas e sabedoria militar. Gostaria de aprender com você.'),
(244, 'Sun Tzu: A sabedoria não é dada, é adquirida através da prática e da observação. O que você tem para oferecer em troca?'),
(245, 'Protagonista: Trago experiência e uma mente aberta. Estou disposto a aprender e aplicar seus ensinamentos.'),
(246, 'Sun Tzu: Então, prove seu valor. Mostre-me que você é digno de aprender os princípios da guerra e da estratégia.'),

(247, 'Protagonista: Você é Beowulf, o herói dos antigos contos?'),
(248, 'Beowulf: Sim, sou ele. O que te traz a mim, estranho?'),
(249, 'Protagonista: Ouvi falar de suas façanhas e das grandes batalhas que enfrentou. Gostaria de ouvir mais sobre suas histórias.'),
(250, 'Beowulf: Minhas histórias são muitas e não são para serem ouvidas de uma só vez. O que procura aprender com elas?'),
(251, 'Protagonista: Desejo entender o que faz de você um verdadeiro herói e como enfrentar os desafios que surgem no meu caminho.'),
(252, 'Beowulf: Então ouça com atenção e prepare-se para agir com coragem e honra. Um herói é definido pelas suas ações e pelo seu caráter.'),

(253, 'Protagonista: Você é Ramsés, o grande faraó do Egito?'),
(254, 'Ramsés: Sim, sou ele. E você, quem é que ousa se apresentar diante de mim?'),
(255, 'Protagonista: Sou apenas um viajante em busca de sabedoria e de conhecer grandes figuras da história.'),
(256, 'Ramsés: A sabedoria é um bem precioso. O que deseja aprender com um governante que dominou terras e povos?'),
(257, 'Protagonista: Quero entender como governar com justiça e como liderar com coragem, assim como você fez.'),
(258, 'Ramsés: Então ouça com atenção. Um líder deve ser justo, mas também firme. A grandeza vem de se manter resoluto frente aos desafios.'),

(259, 'Protagonista: Cleópatra? A lendária rainha do Egito?'),
(260, 'Cleópatra: Sim, sou eu. E quem é você que se atreve a se aproximar da rainha?'),
(261, 'Protagonista: Sou um viajante curioso, fascinado pela história e pela grandiosidade de seu reinado.'),
(262, 'Cleópatra: Curioso, hein? O que deseja saber sobre mim ou sobre o Egito?'),
(263, 'Protagonista: Quero entender como você conseguiu manter o poder e a influência em uma época tão tumultuada.'),
(264, 'Cleópatra: O segredo está em se aliar aos poderosos e saber quando ser persuasiva. O poder, assim como o amor, pode ser conquistado e manipulado.'),

(265, 'Protagonista: Você é Tamerlane, o grande conquistador?'),
(266, 'Tamerlane: Sim, sou eu. E quem é o ousado que se atreve a falar com o senhor dos desfiladeiros?'),
(267, 'Protagonista: Sou apenas um viajante, impressionado com suas conquistas e o legado que deixou.'),
(268, 'Tamerlane: Um viajante, você diz? Então diga-me, o que busca em minha presença?'),
(269, 'Protagonista: Quero aprender sobre sua estratégia e como você conseguiu unir e expandir um império tão vasto.'),
(270, 'Tamerlane: A chave está na estratégia implacável e na força. Um líder deve inspirar lealdade e temeridade ao mesmo tempo.'),

(271, 'Protagonista: Você é Aladdin? O famoso mago das lendas?'),
(272, 'Aladdin: Sim, sou eu. E quem é você, que me reconhece entre tantos?'),
(273, 'Protagonista: Sou um viajante em busca de aventuras e histórias. Sempre ouvi falar de suas façanhas.'),
(274, 'Aladdin: Ah, aventureiro! Então você conhece as minhas aventuras com a lâmpada mágica e o gênio?'),
(275, 'Protagonista: Sim, e estou curioso para saber como foi encontrar e usar a lâmpada mágica.'),
(276, 'Aladdin: Foi uma jornada cheia de desafios e descobertas. A lâmpada trouxe poderes imensos, mas também grandes responsabilidades.'),
(277, 'Protagonista: Você é Ragnar, o famoso guerreiro viking?'),
(278, 'Ragnar: Sim, esse sou eu. E quem é você, que me aborda com tanta confiança?'),
(279, 'Protagonista: Sou um viajante em busca de histórias e batalhas lendárias. Ouvi muito sobre suas conquistas.'),
(280, 'Ragnar: Ah, entendo. O que você gostaria de saber sobre minhas aventuras e conquistas?'),
(281, 'Protagonista: Estou curioso sobre suas batalhas mais memoráveis e como você se tornou uma lenda.'),
(282, 'Ragnar: Minhas batalhas foram duras e as vitórias suadas, mas cada uma delas forjou meu caminho e a história que você conhece.'),
(283, 'Protagonista: Você é Morgana, a famosa feiticeira?'),
(284, 'Morgana: Sim, sou eu. E você, quem é para me abordar com tanta familiaridade?'),
(285, 'Protagonista: Sou apenas um viajante curioso. Ouvi falar muito sobre suas habilidades mágicas e sua história.'),
(286, 'Morgana: Ah, um curioso. O que exatamente deseja saber sobre minha magia e minha trajetória?'),
(287, 'Protagonista: Estou interessado em entender suas motivações e como você se tornou uma figura tão poderosa.'),
(288, 'Morgana: Minhas motivações são profundas e complexas, moldadas por eventos passados e pela busca de poder e vingança.'),
(289, 'Protagonista: Você é Genghis Khan?'),
(290, 'Genghis Khan: Sim, sou ele. E quem é você para me fazer tal pergunta?'),
(291, 'Protagonista: Sou apenas um viajante em busca de conhecimento. Ouvi falar muito sobre suas conquistas e seu império.'),
(292, 'Genghis Khan: Meu império foi forjado através de batalhas e estratégia. O que deseja saber sobre meus feitos?'),
(293, 'Protagonista: Quero entender o que o motivou a construir um império tão vasto e qual é o seu legado.'),
(294, 'Genghis Khan: Meu legado é o domínio e a unificação de terras vastas. Foi a força e a determinação que moldaram meu caminho.'),
(295, 'Protagonista: Você é Joan of Arc, a heroína francesa?'),
(296, 'Joan of Arc: Sim, sou ela. E você, quem é para me encontrar em meus momentos de missão?'),
(297, 'Protagonista: Sou um viajante em busca de histórias e sabedoria. Ouvi muito sobre suas batalhas e sua devoção.'),
(298, 'Joan of Arc: Minha luta foi pelo meu país e pela justiça. O que deseja saber sobre minha jornada?'),
(299, 'Protagonista: Quero entender o que a motivou a liderar e qual foi o impacto de suas ações.'),
(300, 'Joan of Arc: Acredito que minha fé e o desejo de libertar minha nação foram o que me guiou. Espero que meu legado inspire outros a lutar por suas causas.'),
(301, 'Protagonista: Você é Marco Polo, o famoso explorador?'),
(302, 'Marco Polo: Sim, esse sou eu. Quem você é e o que o trouxe até mim?'),
(303, 'Protagonista: Sou um viajante em busca de conhecimentos e histórias. Fiquei fascinado com suas aventuras.'),
(304, 'Marco Polo: Ah, uma busca por conhecimento! Então, qual parte de minhas viagens desperta sua curiosidade?'),
(305, 'Protagonista: Gostaria de saber mais sobre suas experiências na China e como era a vida na corte de Kublai Khan.'),
(306, 'Marco Polo: A China era um lugar de grande riqueza e mistério. A corte de Kublai Khan era imponente, e eu aprendi muito sobre governança e cultura.'),
(307, 'Protagonista: Você é realmente Robin Hood?'),
(308, 'Robin Hood: Sim, sou eu mesmo. E você, o que faz por aqui em Sherwood?'),
(309, 'Protagonista: Ouvi histórias sobre você e suas façanhas. Estou curioso para saber mais sobre sua causa.'),
(310, 'Robin Hood: Nossa causa é simples, combater a injustiça e roubar dos ricos para dar aos pobres. E o que o trouxe até nós?'),
(311, 'Protagonista: Vim em busca de justiça e liberdade. Suas ações me inspiraram a lutar contra a opressão.'),
(312, 'Robin Hood: Então você também é um aliado na luta contra a tirania. Junte-se a nós, e juntos podemos fazer a diferença.'),
(313, 'Protagonista: Você é realmente Vlad III?'),
(314, 'Vlad III: Sim, sou Vlad, também conhecido como Vlad Tepes. E você, quem é que se atreve a me enfrentar?'),
(315, 'Protagonista: Ouvi rumores sobre suas ações e sua história. O que você busca em sua luta?'),
(316, 'Vlad III: Minha busca é pela justiça e pela preservação de meu reino. Muitos não entendem os métodos que uso, mas são necessários.'),
(317, 'Protagonista: Entendo que seus métodos possam ser brutais, mas qual é a sua verdadeira intenção?'),
(318, 'Vlad III: Minha intenção é proteger meu povo e minha terra. Se isso significa usar o medo para garantir a ordem, então assim o farei.'),
(319, 'Protagonista: Você é Kublai Khan? Ouvi falar muito sobre suas conquistas.'),
(320, 'Kublai Khan: Sim, sou Kublai Khan, o grande imperador dos Mongóis. E você, quem é que se apresenta diante de mim?'),
(321, 'Protagonista: Estou aqui para entender mais sobre seus feitos e o que realmente o motivou a expandir seu império.'),
(322, 'Kublai Khan: Meu objetivo sempre foi unificar as terras sob um governo forte e justo. A expansão é apenas uma parte disso.'),
(323, 'Protagonista: Seu império alcançou muitas terras. Como você lida com a administração de tão vasto território?'),
(324, 'Kublai Khan: A administração é uma tarefa desafiadora, mas conto com conselheiros sábios e sistemas eficientes para manter a ordem e prosperidade.'),
(61, 'Protagonista: Quem é você, e por que parece tão imponente?'),
(62, 'Iskandar: Eu sou Iskandar, também conhecido como Alexandre, o Grande. Meu império se estende além das fronteiras que você conhece.'),
(63, 'Protagonista: O que trouxe você para este lugar?'),
(64, 'Iskandar: Meu desejo é conhecer novas terras e desafios. Cada conquista é uma oportunidade para provar meu valor.'),
(65, 'Protagonista: E qual é o seu objetivo aqui?'),
(66, 'Iskandar: Meu objetivo é expandir meus horizontes e testar minha força. Este mundo tem muito a oferecer, e eu estou aqui para explorá-lo.'),
(325, 'Protagonista: Quem é você, e por que tem essa aura de autoridade?'),
(326, 'Ozymandias: Eu sou Ozymandias, o grande rei dos reis. Minha grandeza é evidente para todos que cruzam meu caminho.'),
(327, 'Protagonista: O que exatamente você busca aqui?'),
(328, 'Ozymandias: Busco manter e expandir meu domínio. Este mundo é apenas mais uma peça em meu vasto império.'),
(329, 'Protagonista: Qual é a sua visão para o futuro?'),
(330, 'Ozymandias: Meu futuro é uma continuação de meu legado imortal. Eu busco a eternidade através da grandeza e da conquista.'),
(331, 'Protagonista: Quem é você? Não parece ser alguém comum.'),
(332, 'Quetzalcoatl: ¡Hola! Sou Quetzalcoatl, a deusa da luz e da bondade. Uma guerreira do céu e da terra.'),
(333, 'Protagonista: Uma deusa? O que você faz aqui?'),
(334, 'Quetzalcoatl: Vim para oferecer minha ajuda. Onde houver uma batalha justa, estarei presente com minha força divina!'),
(335, 'Protagonista: Você parece bem alegre para alguém tão poderoso.'),
(336, 'Quetzalcoatl: Hehe, a vida é para ser celebrada! A força sem alegria é inútil, meu amigo.');