--- NPCS

INSERT INTO npc (id_npc, nome, alinhamento, biografia, residencia, qtd_iteracao) VALUES
(1, 'Artoria', 'good', 'Rei lendário da Bretanha que empunha Excalibur.', 16, 5),
(2, 'Gilgamesh', 'neutral', 'O Rei de Uruk, considerado o mais antigo herói da humanidade.', 24, 3),
(3, 'Medusa', 'neutral', 'A famosa Górgona da mitologia grega, amaldiçoada com olhos petrificantes.', 25, 7),
(4, 'Jeanne', 'good', 'A santa francesa que lutou pelo povo e pela liberdade.', 17, 10),
(5, 'Emiya', 'neutral', 'Um herói trágico que sacrifica tudo para salvar o futuro.', 35, 8),
(6, 'Karna', 'good', 'O herói lendário da mitologia indiana, filho do deus sol.', 36, 4),
(7, 'Heracles', 'neutral', 'O herói mais famoso da Grécia, conhecido por seus Doze Trabalhos.', 37, 6),
(8, 'Ozymandias', 'evil', 'O faraó divino, que se acredita ser o deus da realeza.', 38, 2),
(9, 'Mash', 'good', 'Uma jovem que se tornou um Shielder e protege aqueles ao seu redor.', 39, 1),
(10, 'Angra Mainyu', 'evil', 'A personificação do mal zoroastriano que traz calamidade ao mundo.', 55, 9),
(11, 'Cu Chulainn', 'neutral', 'O herói lendário da Irlanda, famoso por suas proezas com a Gáe Bolg.', 57, 6),
(12, 'Iskandar', 'good', 'O Rei dos Conquistadores, Alexandre, o Grande.', 15, 4),
(13, 'Scáthach', 'neutral', 'A rainha guerreira da Terra das Sombras, mestre de Cu Chulainn.', 63, 7),
(14, 'Merlin', 'good', 'O lendário mago e conselheiro do rei Artoria.', 65, 3),
(15, 'Lancelot', 'neutral', 'Cavaleiro da Távola Redonda que caiu em desgraça por seu amor proibido.', 77, 2),
(16, 'Nero', 'good', 'A imperatriz de Roma, conhecida por sua paixão e bravura.', 85, 5),
(17, 'Tamamo', 'evil', 'Uma raposa divina da mitologia japonesa com poderes místicos.', 92, 8),
(18, 'Okita', 'good', 'Uma espadachim lendária do Shinsengumi.', 101, 10),
(112, 'Arjuna', 'neutral', 'O lendário arqueiro da mitologia indiana, rival de Karna.', 116, 4),
(20, 'Medb', 'evil', 'A rainha da província irlandesa de Connacht, famosa por sua ambição.', 121, 9),
(21, 'Siegfried', 'good', 'O famoso herói que derrotou o dragão Fafnir e se banhou no seu sangue.', 130, 5),
(22, 'François', 'neutral', 'Um cavaleiro lendário da França, conhecido pela sua bravura em batalha.', 138, 4),
(23, 'Elizabeth', 'evil', 'A famosa vampira e governante tirânica que causou o terror no coração de muitos.', 143, 6),
(24, 'Napoleon', 'neutral', 'O famoso líder militar que ascendeu à fama durante a Revolução Francesa.', 150, 8),
(25, 'Altera', 'evil', 'O líder implacável dos hunos, conhecido por sua crueldade e poder destrutivo.', 159, 9),
(26, 'Gawain', 'good', 'O cavaleiro da Távola Redonda, conhecido por sua força e honra em combate.', 161, 7),
(27, 'Tristan', 'neutral', 'O cavaleiro bardo, conhecido por sua trágica história de amor.', 169, 2),
(28, 'Mordred', 'evil', 'O cavaleiro traidor, que liderou a rebelião contra o Rei Artoria.', 177, 5),
(29, 'Cleópatra', 'neutral', 'A última rainha do Egito Ptolemaico, famosa por sua beleza e inteligência.', 181, 3),
(30, 'Nightingale', 'good', 'A famosa enfermeira britânica que salvou vidas durante a Guerra da Crimeia.', 190, 6),
(31, 'Quetzalcoatl', 'neutral', 'A deusa serpente alada da mitologia asteca, conhecida por seu poder.', 198, 7),
(32, 'Atalanta', 'good', 'A caçadora lendária, famosa por sua velocidade e habilidades com arco e flecha.', 198, 4),
(33, 'Ivan', 'neutral', 'O Czar que foi tanto adorado quanto temido pelo seu povo.', 201, 10),
(34, 'Da Vinci', 'good', 'O gênio renascentista, criador de máquinas e estrategista brilhante.', 208, 1),
(35, 'Mata Hari', 'evil', 'A famosa dançarina e espiã, cuja beleza escondia intenções sombrias.', 216, 2),
(36, 'Spartacus', 'neutral', 'O líder rebelde que lutou contra a tirania do Império Romano.', 222, 9),
(37, 'Ereshkigal', 'evil', 'A deusa suméria do submundo, governante dos mortos.', 228, 5),
(38, 'Romulus', 'good', 'O lendário fundador de Roma, símbolo de liderança e força.', 234, 8),
(39, 'Billy the Kid', 'neutral', 'O famoso fora-da-lei do Velho Oeste, conhecido por sua mira impecável.', 243, 6),
(40, 'Dante', 'evil', 'O poeta e cavaleiro, mergulhado em vingança e sombras.', 248, 4),
(41, 'Cleopatra', 'good', 'A última faraó do Egito, conhecida por sua beleza e habilidades diplomáticas.', 253, 5),
(42, 'Leonidas', 'good', 'O rei espartano que liderou os 300 na Batalha das Termópilas.', 263, 6),
(43, 'Sun Tzu', 'neutral', 'O estrategista militar chinês autor de "A Arte da Guerra".', 274, 7),
(44, 'Beowulf', 'good', 'O herói anglo-saxão conhecido por suas batalhas contra monstros como Grendel.', 282, 8),
(45, 'Ramsés', 'evil', 'O faraó egípcio conhecido por seu domínio opressivo e suas campanhas militares.', 283, 4),
(46, 'Cleo', 'neutral', 'Uma sacerdotisa com conhecimentos ocultos e habilidades mágicas.', 312, 5),
(47, 'Tamerlane', 'evil', 'O conquistador turco-mongol conhecido por sua brutalidade e ambição.', 295, 6),
(48, 'Aladdin', 'neutral', 'O jovem que encontrou uma lâmpada mágica e fez amizade com um gênio.', 302, 7),
(49, 'Ragnar', 'good', 'O líder viking e guerreiro conhecido por suas expedições e batalhas.', 304, 4),
(50, 'Morgana', 'evil', 'A feiticeira da lenda arturiana, conhecida por sua traição e habilidades mágicas.', 323, 5),
(51, 'Genghis Khan', 'evil', 'O fundador do Império Mongol, conhecido por suas conquistas e táticas militares.', 324, 6),
(52, 'Joan of Arc', 'good', 'A heroína francesa que lutou contra os ingleses e foi martirizada.', 331, 7),
(53, 'Marco Polo', 'neutral', 'O explorador veneziano que viajou por várias terras e trouxe conhecimento de novas culturas.', 342, 8),
(54, 'Robin Hood', 'good', 'O fora da lei inglês conhecido por roubar dos ricos e dar aos pobres.', 343, 6),
(55, 'Vlad III', 'evil', 'O governante que inspirou a lenda do Drácula e era conhecido por sua crueldade.', 352, 5),
(56, 'Kublai Khan', 'neutral', 'O imperador mongol da dinastia Yuan, conhecido por sua administração e conquistas na China.', 361, 5);